=== resource-reasoning/resourcereasoning.com/_schema/papers.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Papers",

  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "title": {
        "type": "string"
      },
      "authors": {
        "type": "string"
      },
      "abstract": {
        "type": "string",
        "format": "markdown"
      },
      "bibtex": {
        "type": "string"
      },
      "pubdate": {
        "type": "string",
        "format": "date"
      },
      "venue": {
        "type": "string"
      },
      "pdf": {
        "type": "string",
        "format": "url"
      },
      "pdflong": {
        "type": "string",
        "format": "url"
      },
      "ps": {
        "type": "string",
        "format": "url"
      },
      "pslong": {
        "type": "string",
        "format": "url"
      }
    },
    "additionalProperties": false,
    "required": ["title", "authors", "abstract", "pubdate", "venue"],
    "anyOf": [
      { "required": ["pdf"] },
      { "required": ["pdflong"] },
      { "required": ["ps"] },
      { "required": ["pslong"] }
    ],

    "options": {
      "remove_empty_properties": true
    }
  },

  "additionalItems": false,
  "format": "tabs"
}

=== resource-reasoning/resourcereasoning.com/_data/papers.json
[  { 
   "abstract": "",
    "authors": "M. Collinson, K. McDonald, and D. Pym",
    "bibtex": "",
    "pdf": "",
    "pdflong": "",
    "pubdate": "2015",
    "title": "Layered Graph Logic as an Assertion Language for Access Control Policy Model",
    "venue": "Accepted for publication, Journal of Logic and Computation"
  },
  { 
   "abstract": "",
    "authors": "G. Anderson and D. Pym",
    "bibtex": "",
    "pdf": "",
    "pdflong": "",
    "pubdate": "2015",
    "title": "Combinators for Trust Domains in Security Modelling",
    "venue": "Accepted for publication, Journal of Logic and Computation"
  },
  { 
   "abstract": "",
    "authors": "M. Collinson, K. McDonald, and D. Pym",
    "bibtex": "",
    "pdf": "",
    "pdflong": "http://www.doc.ic.ac.uk/~td202/papers/vsttepfs.pdf",
    "pubdate": "2014",
    "title": "A Substructural Logic for Layered Graphs",
    "venue": "Journal of Logic and Computation"
  },
  {
    "abstract": "Local reasoning has become a well-established technique in program verification, which has been shown to be useful\nat many different levels of abstraction.  In separation logic, we use a low-level abstraction that is close to how the\nmachine sees the program state. In context logic, we work with high-level abstractions that are close to how the clients\nof modules see the program state.  We apply program refinement to local reasoning, demonstrating that high-level local\nreasoning is sound for module implementations.  We consider two approaches: one that preserves the high-level locality\nat the low level;  and one that breaks the high-level \"fiction\" of locality.\n",
    "authors": "Thomas Dinsdale-Young, Philippa Gardner, Mark Wheelhouse",
    "bibtex": "@INPROCEEDINGS{DGW10,\n  author = {Dinsdale-Young, Thomas and Gardner, Philippa and Wheelhouse, Mark},\n  title = {Abstraction and Refinement for Local Reasoning},\n  booktitle = {Proceedings of the Third international conference on Verified software:\n\ttheories, tools, experiments},\n  year = {2010},\n  pages = {199--215},\n  address = {Berlin, Heidelberg},\n  publisher = {Springer-Verlag}\n}\n",
    "pdf": "http://www.doc.ic.ac.uk/~td202/papers/vstte2010.pdf",
    "pdflong": "http://www.doc.ic.ac.uk/~td202/papers/vsttepfs.pdf",
    "pubdate": "2010-08-16",
    "title": "Abstraction and Refinement for Local Reasoning",
    "venue": "VSTTE 2010"
  },
  {
    "abstract": "We present _Classical_ BI (CBI), a new addition to the family of _bunched logics_\nwhich originates in O'Hearn and Pym's logic of bunched implications BI. CBI differs from\nexisting bunched logics in that its multiplicative connectives behave classically rather than\nintuitionistically (including in particular a multiplicative version of classical negation). At\nthe semantic level, CBI-formulas have the normal bunched logic reading as declarative\nstatements about resources, but its resource models necessarily feature more structure\nthan those for other bunched logics; principally, they satisfy the requirement that every\nresource has a unique dual. At the proof-theoretic level, a very natural formalism for CBI\nis provided by a display calculus _à la_ Belnap, which can be seen as a generalisation of the\nbunched sequent calculus for BI. In this paper we formulate the aforementioned model\ntheory and proof theory for CBI, and prove some fundamental results about the logic,\nmost notably completeness of the proof theory with respect to the semantics.\n",
    "authors": "James Brotherston, Cristiano Calcagno",
    "bibtex": "@Article{Brotherston-Calcagno:10,\n  author    = \"James Brotherston and Cristiano Calcagno\",\n  title     = \"Classical {BI}: {I}ts Semantics and Proof Theory\",\n  journal   = \"Logical Methods in Computer Science\",\n  volume    = 6,\n  number    = 3,\n  year      = 2010\n}\n",
    "pdf": "http://arxiv.org/pdf/1005.2340",
    "ps": "http://arxiv.org/ps/1005.2340",
    "pubdate": "2010-07-20",
    "title": "Classical BI: Its Semantics and Proof Theory",
    "venue": "Logical Methods in Computer Science, 2010"
  },
  {
    "abstract": "We present a proof of safety and linearizability of a highly-concurrent\noptimistic set algorithm. The key step in our proof\nis the Hindsight Lemma, which allows a thread to infer the existence\nof a global state in which its operation can be linearized\nbased on limited local atomic observations about the shared state.\nThe Hindsight Lemma allows us to avoid one of the most complex\nand non-intuitive steps in reasoning about highly concurrent algorithms:\nconsidering the linearization point of an operation to be in\na different thread than the one executing it.\n\nThe Hindsight Lemma assumes that the algorithm maintains certain\nsimple invariants which are resilient to interference, and which\ncan themselves be verified using purely thread-local proofs. As a\nconsequence, the lemma allows us to unlock a perhaps-surprising\nintuition: a high degree of interference makes non-trivial highly-concurrent\nalgorithms in some cases much easier to verify than less\nconcurrent ones.\n",
    "authors": "Peter W. O'Hearn, Noam Rinetzky, Martin T. Vechev, Eran Yahav, Greta Yorsh",
    "bibtex": "@INPROCEEDINGS{ORV+10,\n  author = {O'Hearn, Peter W. and Rinetzky, Noam and Vechev, Martin T. and Yahav,\n\tEran and Yorsh, Greta},\n  title = {Verifying Linearizability with Hindsight},\n  booktitle = {Proceedings of the 29th ACM SIGACT-SIGOPS symposium on Principles\n\tof Distributed Computing},\n  year = {2010},\n  pages = {85--94},\n  address = {New York, NY, USA},\n  publisher = {ACM}\n}\n",
    "pdf": "http://www0.cs.ucl.ac.uk/staff/p.ohearn/papers/podc2010.pdf",
    "pubdate": "2010-07-25",
    "title": "Verifying Linearizability with Hindsight",
    "venue": "PODC 2010"
  },
  {
    "abstract": "Modern object-oriented languages support higher-order implementations through function objects such as delegates\nin C#, agents in Eiffel, or closures in Scala. Function objects bring a new level of abstraction to the\nobject-oriented programming model, and require a comparable extension to specification and verification techniques.\nWe introduce a verification methodology that extends function objects with auxiliary side-effect free (pure)\nmethods to model logical artifacts: preconditions, postconditions and modifies clauses. These pure methods can be\nused to specify client code abstractly, that is, independently from specific instantiations of the function\nobjects. To demonstrate the feasibility of our approach, we have implemented an automatic prover, which verifies\nseveral non-trivial examples.\n",
    "authors": "Martin Nordio, Cristiano Calcagno, Bertrand Meyer, Peter Müller, Julian Tschannen",
    "bibtex": "@INPROCEEDINGS{NCM+10,\n  author = {Martin Nordio and Cristiano Calcagno and Bertrand Meyer and Peter M{\\\"u}ller and Julian Tschannen},\n  title = {Reasoning about Function Objects},\n  booktitle = {Proceedings of the 48th international conference on Objects, Models,\n\tComponents and Patterns},\n  year = {2010},\n  pages = {79--96},\n  address = {Berlin, Heidelberg},\n  publisher = {Springer-Verlag}\n}\n",
    "pdf": "http://se.ethz.ch/~meyer/publications/proofs/agents.pdf",
    "pubdate": "2010-06-28",
    "title": "Reasoning about Function Objects",
    "venue": "TOOLS Europe 2010"
  },
  {
    "abstract": "Specifications of Object-Oriented programs conventionally\nemploy Boolean expressions of the programming language for assertions.\nProgramming errors can be discovered by checking at runtime whether\nan assertion, such as a precondition or class invariant, holds. In this work,\nwe show how separation logic can be used to verify that these executable\nspecifications will always hold at runtime. Both the program and its executable\nassertions are verified with respect to separation logic specifications.\nA novel notion called _relative purity_ embraces historically problematic\nside-effects in executable specifications, and verification boils down\nto proving _connecting implications_. Even model-based specifications can\nbe verified. The framework is also well-suited to separation logic proof\ntools and now implemented in jStar. Numerous automatically verified\nexamples illustrate the framework's use and utility.\n",
    "authors": "Stephan van Staden, Cristiano Calcagno, Bertrand Meyer",
    "bibtex": "@INPROCEEDINGS{vSCM10,\n  author = {Stephan van Staden and Cristiano Calcagno and Bertrand Meyer},\n  title = {Verifying Executable Object-Oriented Specifications with Separation\n\tLogic},\n  booktitle = {Proceedings of the 24th European conference on Object-oriented programming},\n  year = {2010},\n  pages = {151--174},\n  address = {Berlin, Heidelberg},\n  publisher = {Springer-Verlag}\n}\n",
    "pdf": "http://se.ethz.ch/~meyer/publications/proofs/ooseparation.pdf",
    "pubdate": "2010-06-21",
    "title": "Verifying Executable Object-Oriented Specifications with Separation Logic",
    "venue": "ECOOP 2010"
  },
  {
    "abstract": "Abstraction is key to understanding and reasoning about large computer systems. Abstraction is simple to achieve\nif the relevant data structures are disjoint, but rather difficult when they are partially shared, as is often the\ncase for concurrent modules. We present a program logic for reasoning abstractly about data structures that\nprovides a fiction of disjointness and permits compositional reasoning. The internal details of a module are\ncompletely hidden from the client by _concurrent abstract predicates_. We reason about a module's\nimplementation using separation logic with permissions, and provide abstract specifications for use by client\nprograms using concurrent abstract predicates. We illustrate our abstract reasoning by building two\nimplementations of a lock module on top of hardware instructions, and two implementations of a concurrent set\nmodule on top of the lock module.\n",
